### ISSUE TITLE
Modt -e command not found

### ISSUE THREAD

**Issue by Joly0** [ich777/docker-lancache-prefill#4]
![grafik](https://user-images.githubusercontent.com/13993216/218888254-cf8e6542-9385-49f7-bffc-2fcb2c634e56.png)

**Comment by Joly0** [comment]
![grafik](https://user-images.githubusercontent.com/13993216/218888465-d73a111a-3fa5-457a-9369-3a30c6bc2d38.png)

**Comment by ich777** [comment]
@Joly0 thank you for the report, I don't know why it inserts `-e` at all. I have now tried many different things and given up adding a new line before the injected message, don't know why it won't work...
Please update the container.
