### ISSUE TITLE
Wrong link to repo in Unraid Docker

### ISSUE THREAD

**Issue by pascalschmiederer** [ich777/docker-lancache-prefill#7]
The link to your Repo is in the unraid Docker from Appstore wrong.

OLD: [ich777/lancache-prefill](https://github.com/ich777/lancache-prefill)
NEW: https://github.com/ich777/docker-lancache-prefill

**Comment by ich777** [comment]
Thank you for the report, the link to the registry is completely wrong because it has to point to Docker Hub, the correct link is: `https://hub.docker.com/r/ich777/lancache-prefill`

I've already changed that in the template but it will take usually a few hours to reflect that change in the CA App.
