### ISSUE TITLE
Export --os Parameter

### ISSUE THREAD

**Issue by pascalschmiederer** [ich777/docker-lancache-prefill#9]
It would be great if you can export the --os Paramter 

https://tpill90.github.io/steam-lancache-prefill/detailed-command-usage/Prefill/

Or perhaps it would be easier to include an external script folder that automatically executes the .sh scripts it contains

**Comment by ich777** [comment]
> It would be great if you can export the --os Paramter

I think you should first read [this](https://github.com/ich777/docker-lancache-prefill#env-params).

By default the container passes through `--recent` to SteamPrefill through `PREFILL_PARAMS_STEAM` I assume you know where this is going... ;)

**Comment by pascalschmiederer** [comment]
Nice. :) Not seen it before.

But the second one: Export the userscripts folder?

**Comment by ich777** [comment]
> Not seen it before.

If you are on Unraid even the template states that (~~with the link that you've provided above~~ okay, the link is broken but I'll fix that).

> But the second one: Export the userscripts folder?

I don't understand what you mean with that at least not fully...
Why would you need that, you can do everything with the variables.

You even can execute schedules directly in the container for each Prefill on it's own or a global schedule which executes one after the other (if enabled).

**Comment by pascalschmiederer** [comment]
No not all. Or I dont know how. 

I want to download Linux and Windows games. And "--os linux, windows" doesn't work.

Alternatively, I could install the docker twice

**Comment by ich777** [comment]
> I want to download Linux and Windows games. And "--os linux, windows" doesn't work.

What does not work? What is the log output or what does it say? It is really hard to troubleshoot with "it does not work".
If you enter the arguments like described in the documentation it should work just fine.

> Alternatively, I could install the docker twice

Because you can't pass over two arguments I assume?

@tpill90 can you join in here please? This should work correct? Does it download first Windows and then Linux I assume?
Could it be the case because my container always passes through `--no-ansi` first and then all other arguments?

**Comment by pascalschmiederer** [comment]
There is no difference between "linux + windows" and "windows" in the logs!

Maybe everything is working correctly, but I don't see it.


=============================================================================================


`root@8250e9c28973:/# ${DATA_DIR}/SteamPrefill/SteamPrefill prefill --no-ansi --os linux windows --verbose
[6:42:58 PM] Starting login!
[6:42:58 PM] Connecting with CellId: 5
Connecting to Steam...
[6:42:59 PM] Connected to Steam!
Logging in to Steam...
[6:43:00 PM] Logged into Steam
[6:43:00 PM] Unable to determine CM geolocation info
Retrieving owned apps...
[6:43:00 PM] Loaded account licenses                             00.3120
[6:43:00 PM] Steam session initialization complete!              02.1062

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Retrieving latest App metadata...
[6:43:01 PM] Loaded metadata for 5 apps                          00.8650
[6:43:02 PM] Loaded metadata for 3 apps                          00.6446

[6:43:02 PM] Prefill complete!
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Prefilled 5 apps totaling 0 b in 04.0391 
                                           
   Updated │ Up To Date                    
  ━━━━━━━━━┿━━━━━━━━━━━━                   
      0    │     5                         
                                           
Disconnecting
[6:43:02 PM] Disconnected from Steam!`

`root@8250e9c28973:/# ${DATA_DIR}/SteamPrefill/SteamPrefill prefill --no-ansi --os windows --verbose
[6:44:13 PM] Starting login!
[6:44:13 PM] Connecting with CellId: 5
Connecting to Steam...
[6:44:15 PM] Connected to Steam!
Logging in to Steam...
[6:44:16 PM] Logged into Steam
[6:44:16 PM] Unable to determine CM geolocation info
Retrieving owned apps...
[6:44:17 PM] Loaded account licenses                             00.4798
[6:44:17 PM] Steam session initialization complete!              03.9790

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Retrieving latest App metadata...
[6:44:18 PM] Loaded metadata for 5 apps                          01.0293
[6:44:19 PM] Loaded metadata for 3 apps                          00.9870

[6:44:19 PM] Prefill complete!
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Prefilled 5 apps totaling 0 b in 06.4051 
                                           
   Updated │ Up To Date                    
  ━━━━━━━━━┿━━━━━━━━━━━━                   
      0    │     5                         
                                           
Disconnecting
[6:44:19 PM] Disconnected from Steam!`

`root@8250e9c28973:/# ${DATA_DIR}/SteamPrefill/SteamPrefill prefill --no-ansi --os linux --verbose
[6:44:53 PM] Starting login!
[6:44:53 PM] Connecting with CellId: 5
Connecting to Steam...
[6:44:54 PM] Connected to Steam!
Logging in to Steam...
[6:44:55 PM] Logged into Steam
[6:44:55 PM] Unable to determine CM geolocation info
Retrieving owned apps...
[6:44:55 PM] Loaded account licenses                             00.3412
[6:44:55 PM] Steam session initialization complete!              02.2419

────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Retrieving latest App metadata...
[6:44:56 PM] Loaded metadata for 5 apps                          00.7874
[6:44:57 PM] Loaded metadata for 3 apps                          00.7946

[6:44:57 PM] Starting Atomic Heart  No depots to download.  Current arguments filtered all depots
[6:44:57 PM] Starting Die drei ??? - Rätsel aus der Geisterwelt  No depots to download.  Current arguments filtered all depots
[6:44:57 PM] Starting Plants vs. Zombies: Game of the Year  No depots to download.  Current arguments filtered all depots
[6:44:57 PM] Prefill complete!
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Prefilled 2 apps totaling 0 b in 04.2308 
                                           
   Updated │ Up To Date                    
  ━━━━━━━━━┿━━━━━━━━━━━━                   
      0    │     2                         
                                           
Disconnecting
[6:44:57 PM] Disconnected from Steam!`

https://github.com/tpill90/steam-lancache-prefill/issues/344

**Comment by ich777** [comment]
> ${DATA_DIR}/SteamPrefill/SteamPrefill prefill --no-ansi --os linux windows --verbose

Are you sure that `,` is not missing here between `linux` and `windows`?

Please also keep in mind that not every game on Steam has a Linux version available since most of the games are nowadays run through Proton.

**Comment by tpill90** [comment]
That's likely what's going on here. Not everything has a native Linux version. And the ones that do usually share the assets which is the largest part of the download.  For example the Linux specific depot for counter strike is only a few hundred mb so you'd barely even notice the difference

**Comment by pascalschmiederer** [comment]
I thought that the log shows me what I selected and/or count all the selected games:

Up to date:

5 games for --os windows
2 games for --os linux
7 games for --os windows linux 


But if it is not so, then I will check it with the next updates and will report in the tickets.

**Comment by pascalschmiederer** [comment]
Prefill for Linux works not as expected:

1. I manually prefilled and got a 5/5 or 2/2 updated but there are no hits if I update the game via Steam!
2. If I delete the game in Steam and reinstall it, I get the cache hits for the game. 

So config and IPs seems to be ok. But the prefiller get not all the used files. 



`root@f4477702c8d4:/# /lancacheprefill/SteamPrefill/SteamPrefill prefill --os linux windows
[11:17:23 AM] Starting login!
[11:17:24 AM] Connected to Steam!
[11:17:25 AM] Logged into Steam
[11:17:25 AM] Unable to determine CM geolocation info
[11:17:26 AM] Loaded account licenses                            00.3793
[11:17:26 AM] Steam session initialization complete!             02.4033

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

[11:17:28 AM] Prefill complete!
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Prefilled 5 apps totaling 0 b in 05.1291 
                                           
   Updated │ Up To Date                    
  ━━━━━━━━━┿━━━━━━━━━━━━                   
      0    │     5                         
                                           
[11:17:28 AM] Disconnected from Steam!
root@f4477702c8d4:/# /lancacheprefill/SteamPrefill/SteamPrefill prefill --os linux
[11:17:35 AM] Starting login!
[11:17:36 AM] Connected to Steam!
[11:17:37 AM] Logged into Steam
[11:17:37 AM] Unable to determine CM geolocation info
[11:17:37 AM] Loaded account licenses                            00.3952
[11:17:37 AM] Steam session initialization complete!             02.5054

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

[11:17:39 AM] Starting Atomic Heart  No depots to download.  Current arguments filtered all depots
[11:17:39 AM] Starting Die drei ??? - Rätsel aus der Geisterwelt  No depots to download.  Current arguments filtered all depots
[11:17:39 AM] Starting Plants vs. Zombies: Game of the Year  No depots to download.  Current arguments filtered all depots
[11:17:39 AM] Prefill complete!
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  Prefilled 2 apps totaling 0 b in 04.7062 
                                           
   Updated │ Up To Date                    
  ━━━━━━━━━┿━━━━━━━━━━━━                   
      0    │     2                         
                                           
[11:17:39 AM] Disconnected from Steam!`


`[steam] 192.168.1.108 / - - - [07/Jan/2024:11:19:44 +0100] "GET /depot/730/chunk/cabbdbe584da66b390c6966835ea25fb4efb0d48 HTTP/1.1" 200 627600 "-" "Valve/Steam HTTP Client 1.0" "MISS" "steampipe.akamaized.net" "-"
[steam] 192.168.1.108 / - - - [07/Jan/2024:11:19:44 +0100] "GET /depot/730/chunk/9ce618fda399b40bd0f99668e50a85eab09994fe HTTP/1.1" 200 752 "-" "Valve/Steam HTTP Client 1.0" "MISS" "steampipe.akamaized.net" "-"
[steam] 192.168.1.108 / - - - [07/Jan/2024:11:19:46 +0100] "GET /depot/730/chunk/e7b0c91f4379998f89027b8a47b8ede630916d88 HTTP/1.1" 200 615264 "-" "Valve/Steam HTTP Client 1.0" "MISS" "google2.cdn.steampipe.steamcontent.com" "-"
[steam] 192.168.1.108 / - - - [07/Jan/2024:11:19:46 +0100] "GET /depot/730/chunk/37371383dfa08c2babc77af2e6270f1ecf8ae638 HTTP/1.1" 200 613040 "-" "Valve/Steam HTTP Client 1.0" "MISS" "google2.cdn.steampipe.steamcontent.com" "-"
[steam] 192.168.1.108 / - - - [07/Jan/2024:11:19:47 +0100] "GET /depot/730/chunk/782738c2f04a58567525049378600cf85951ae9d HTTP/1.1" 200 616864 "-" "Valve/Steam HTTP Client 1.0" "MISS" "steampipe.akamaized.net" "-"
[steam] 192.168.1.108 / - - - [07/Jan/2024:11:19:48 +0100] "GET /depot/730/chunk/bd06030207a1c6e56b1d7632fda60177014d5ad4 HTTP/1.1" 200 620784 "-" "Valve/Steam HTTP Client 1.0" "MISS" "steampipe.akamaized.net" "-"
[steam] 192.168.1.108 / - - - [07/Jan/2024:11:19:48 +0100] "GET /depot/730/chunk/54402276bb2cbf8cadd0dac4a440bd668d5d8d3e HTTP/1.1" 200 600064 "-" "Valve/Steam HTTP Client 1.0" "MISS" "steampipe.akamaized.net" "-"
[steam] 192.168.1.108 / - - - [07/Jan/2024:11:19:49 +0100] "GET /depot/730/chunk/58d908e95507f37abe39a0f4bdc33e184594025b HTTP/1.1" 200 616768 "-" "Valve/Steam HTTP Client 1.0" "MISS" "steampipe.akamaized.net" "-"
[steam] 192.168.1.108 / - - - [07/Jan/2024:11:19:50 +0100] "GET /depot/730/chunk/756fb24e00c8b0a5eb337c586e644b4f94d696b3 HTTP/1.1" 200 605680 "-" "Valve/Steam HTTP Client 1.0" "MISS" "steampipe.akamaized.net" "-"
`

**Comment by ich777** [comment]
> Prefill for Linux works not as expected:

Have you yet tried to prefill a game with native Linux support like Civilization V?

As far as I can tell PvZ GotY, Die drei ??? & Atomic Heart only have OSX or in the case for Atomic Hear only have Windows support.

I don't see what other games you've tried to prefill since it looks like you are prefilling five games.

However the container seems to work fine except for the issue where prefill doesn't download the Linux versions correct?

**Comment by pascalschmiederer** [comment]
I tested it with CS2

But yes. I think the problem is not the container.

**Comment by ich777** [comment]
> I tested it with CS2

What is the other app that it prefilled?

What about my last paragraph from above?

It would also maybe be a good idea to change the title because passing over that argumt is prossible.

**Comment by ich777** [comment]
@pascalschmiederer if possible please open up a new issue [here](https://github.com/tpill90/steam-lancache-prefill/issues) or re-open [#344](https://github.com/tpill90/steam-lancache-prefill/issues/344) since this seems like related to the application that is running inside the container.

**Comment by pascalschmiederer** [comment]
Yes of course
